### ISSUE TITLE
[Business] Regras para entrar

### ISSUE THREAD

**Issue by wouerner** [SouJunior/business#14]

**Comment by wouerner** [comment]
o que está faltando nessa tarefa?

**Comment by maztt** [comment]
Na prática esse card foi gerado por ti e a gente "assumiu" (lembra daqueles que pegamos para fazer?), mas ele acabou sendo ramificado, gerando:

**1. A revisão no FAQ:**
![Image](https://user-images.githubusercontent.com/92126792/213257551-11b5dd27-8577-46cd-942e-0fb7f07d2611.png)

**2. O formulário de entrada,**
https://forms.gle/3WmXJHLHzQSBLKcJ8

**3. que é complementado com os docs** que são disponibilizados lá na última parte: regras de disc, wiki, onboarding e diretrizes de procedimento

lembrete: as diretrizes vão falar sobre aquela base de usar foto, nome do linkedin, instruções de daily, etc.


Talvez a gente possa assumir como encerrado, a não ser que você ainda tenha planos para elaborar requisitos de entrada mais bem descritos. 

O que acha?
