### ISSUE TITLE
[Business] Formulário de Entrada/Preenchimento

### ISSUE THREAD

**Issue by wouerner** [SouJunior/business#7]
* Acrescentar regras para entrar
* Sistema de Read & Understood 
* Discord como filtro (facilitar e agilizar)
* 

______________________

@wouerner @HenriqueJoaoSS

https://forms.gle/MYjLyLX895JBJyxo7

Para validarmos (em todos os sentidos), lembrando que a ideia é deixar isso como um "gatilho"/"trava" inicial para quando as pessoas entrarem no Discord. O ideal seria liberar os acessos somente depois de preencher o formulário, but .........

OBS:
- Ver se realmente utilizaremos;
- Tem validações de formulário básicas;
- "Feio e eficiente";
- Ainda estamos sem as coisas prontas para trilhas de onboarding e diretrizes, então removeremos essas partes, mas no futuro breve colocamos novamente (e repassamos os links com a galera que já teria preenchido);

**Comment by maztt** [comment]
@wouerner @HenriqueJoaoSS 

O que melhorar/acrescentar/remover?

Será que precisamos reduzir o número de páginas? Fiz por seções: uma para coletar dados, uma para coletar time e outra para entregar os "termos iniciais".

Pensei da seguinte forma: imagina que vc entra numa empresa, recebe o seu formulário no primeiro dia e coloca as suas infos pra receber as permissões no sistema e da mesma forma tem acesso às infos mais burocráticas e/ou de folhetozinho de onboarding

**Comment by wouerner** [comment]
@maztt  acredito que finalizou essa tarefa.

**Comment by maztt** [comment]
@wouerner 

Finalizamos, repassei com a Sealtiey sobre incluirmos isso como a "última ação" no processo dos novos entrantes.

Pro futuro alteramos pontualmente o link com as novas documentações que virão e deixarmos maturando a ideia de algum tipo de automatização desse forms.
