### ISSUE TITLE
[Business] Revisão dos Cargos

### ISSUE THREAD

**Issue by maztt** [SouJunior/business#8]
Melhorar e validar o texto em do link: https://github.com/SouJunior/wiki/wiki/Cagos-no-projeto

_____________________

@wouerner @HenriqueJoaoSS avaliarem:

> **CEO**
- Determina as visões de curto, médio e longo prazo para o projeto;
- Acompanha e certifica-se da evolução e progresso do projeto;
- Propõe ideias e repassa demandas ao time de Heads;
- Cuida da relação com os investidores, parcerias e a comunidade, tornando-se porta-voz do projeto;
- Lida com as questões burocráticas, legais e afins do projeto;
- Define a seleção e a composição das equipes de Head e apoia na escolha de Mentores;

> **Heads**
- Promovem um ambiente com ferramentas, processos, quorum e permissões para o desempenho das atividades, seja por parte dos Mentores ou Juniores;
- Garantem a boa comunicação e relação entre membros e as demais áreas;
- Garantem a Gestão do Conhecimento na sua respectiva área;
- Discutem e auxiliam o CEO e a equipe de Heads na elaboração de novos projetos, metas, e no acompanhamento de indicadores;
- Supervisionam e recrutam Mentores;

> **Mentores**
- Garantem o auxílio aos Juniores em suas dúvidas relacionadas às demandas do projeto e de área profissional;
- Promovem dicas, materiais, tutorias e informações que apoiem o desenvolvimento dos Juniores em suas respectivas áreas;
- Validam as demandas entregues pelos Juniores, promovendo qualidade e consistência;

> **Juniores**
- Garantem o cumprimento das demandas de área, dentre atividades e reuniões;
- Identificam as necessidades, impedimentos e potenciais melhorias no operacional a fim de reportar;

**Comment by maztt** [comment]
@wouerner @HenriqueJoaoSS 

Podemos subir isso como versão final para o https://github.com/SouJunior/wiki/wiki/Cargos-no-projeto?

**Comment by wouerner** [comment]
Pode subir.
